export const routes = {
  "/": "/",
  "/login": "/login",
  "/admin": "/admin",
  "/admin/user-groups": "/admin/user-groups",
  "/admin/user-groups/new": "/admin/user-groups/new",
  "/admin/users": "/admin/users",
  "/admin/users/new": "/admin/users/new",
  "/admin/storage": "/admin/storage",
  "/admin/storage/endpoints": "/admin/storage/endpoints",
  "/admin/storage/endpoints/new": "/admin/storage/endpoints/new",
  "/admin/storage/access-templates": "/admin/storage/access-templates",
  "/admin/config": "/admin/config",
  "/admin/config/general": "/admin/config/general",
  "/about": "/about",
} as const
