name: Build on PR

on:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_server:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build server
      run: |
        cd y-server
        cargo build --verbose

  build_web:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build web
      run: |
        cd y-web
        npm install
        npm run lint
        npm run build
